use tee

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -168,56 +168,68 @@ jobs:
         run: bin/rust/vault stack
 
       - name: Store secret with Python
-        run: vault -s 'secret-python' -v 'sha-${{github.sha}}' -w > output.log 2>&1
-      - name: Check output for Python store
-        run: test ! -s output.log || (echo "Unexpected output in Python vault command:" && cat output.log && exit 1)
+        run: |
+          vault -s 'secret-python' -v 'sha-${{github.sha}}' -w 2>&1 | tee output.log
+          test -f output.log || (echo "Error: output.log does not exist!" && exit 1)
+          test -s output.log && (echo "Unexpected output in Python vault command:" && cat output.log && exit 1)
+          rm -f output.log
 
       - name: Retrieve secret with Python
-        run: vault -l 'secret-python' > output.log 2>&1
-      - name: Check output for Python retrieve
         run: |
+          vault -l 'secret-python' 2>&1 | tee output.log
+          test -f output.log || (echo "Error: output.log does not exist!" && exit 1)
           expected="sha-${{github.sha}}"
           actual=$(cat output.log)
           [ "$actual" = "$expected" ] || (echo "Unexpected output in Python vault retrieval:" && cat output.log && exit 1)
+          rm -f output.log
 
       - name: Store secret with Go
-        run: bin/go/vault -s 'secret-go' -v 'sha-${{github.sha}}' -w > output.log 2>&1
-      - name: Check output for Go store
-        run: test ! -s output.log || (echo "Unexpected output in Go vault command:" && cat output.log && exit 1)
+        run: |
+          bin/go/vault -s 'secret-go' -v 'sha-${{github.sha}}' -w 2>&1 | tee output.log
+          test -f output.log || (echo "Error: output.log does not exist!" && exit 1)
+          test -s output.log && (echo "Unexpected output in Go vault command:" && cat output.log && exit 1)
+          rm -f output.log
 
       - name: Retrieve secret with Go
-        run: bin/go/vault -l 'secret-go' > output.log 2>&1
-      - name: Check output for Go retrieve
         run: |
+          bin/go/vault -l 'secret-go' 2>&1 | tee output.log
+          test -f output.log || (echo "Error: output.log does not exist!" && exit 1)
           expected="sha-${{github.sha}}"
           actual=$(cat output.log)
           [ "$actual" = "$expected" ] || (echo "Unexpected output in Go vault retrieval:" && cat output.log && exit 1)
+          rm -f output.log
 
       - name: Store secret with Rust
-        run: bin/rust/vault -s 'secret-rust' -v 'sha-${{github.sha}}' -w > output.log 2>&1
-      - name: Check output for Rust store
-        run: test ! -s output.log || (echo "Unexpected output in Rust vault command:" && cat output.log && exit 1)
+        run: |
+          bin/rust/vault -s 'secret-rust' -v 'sha-${{github.sha}}' -w 2>&1 | tee output.log
+          test -f output.log || (echo "Error: output.log does not exist!" && exit 1)
+          test -s output.log && (echo "Unexpected output in Rust vault command:" && cat output.log && exit 1)
+          rm -f output.log
 
       - name: Retrieve secret with Rust
-        run: bin/rust/vault -l 'secret-rust' > output.log 2>&1
-      - name: Check output for Rust retrieve
         run: |
+          bin/rust/vault -l 'secret-rust' 2>&1 | tee output.log
+          test -f output.log || (echo "Error: output.log does not exist!" && exit 1)
           expected="sha-${{github.sha}}"
           actual=$(cat output.log)
           [ "$actual" = "$expected" ] || (echo "Unexpected output in Rust vault retrieval:" && cat output.log && exit 1)
+          rm -f output.log
 
       - name: Store secret with Nodejs
-        run: nodejs/dist/cli/vault.js s 'secret-nodejs' 'sha-${{github.sha}}' -w > output.log 2>&1
-      - name: Check output for Node.js store
-        run: test ! -s output.log || (echo "Unexpected output in Node.js vault command:" && cat output.log && exit 1)
+        run: |
+          nodejs/dist/cli/vault.js s 'secret-nodejs' 'sha-${{github.sha}}' -w 2>&1 | tee output.log
+          test -f output.log || (echo "Error: output.log does not exist!" && exit 1)
+          test -s output.log && (echo "Unexpected output in Node.js vault command:" && cat output.log && exit 1)
+          rm -f output.log
 
       - name: Retrieve secret with Nodejs
-        run: nodejs/dist/cli/vault.js l 'secret-nodejs' > output.log 2>&1
-      - name: Check output for Node.js retrieve
         run: |
+          nodejs/dist/cli/vault.js l 'secret-nodejs' 2>&1 | tee output.log
+          test -f output.log || (echo "Error: output.log does not exist!" && exit 1)
           expected="sha-${{github.sha}}"
           actual=$(cat output.log)
           [ "$actual" = "$expected" ] || (echo "Unexpected output in Node.js vault retrieval:" && cat output.log && exit 1)
+          rm -f output.log
 
       - name: Validate storing worked Python
         run: diff <(vault -l secret-python) <(echo -n sha-${{github.sha}})
@@ -241,17 +253,32 @@ jobs:
         run: diff <(bin/rust/vault -l secret-rust) <(nodejs/dist/cli/vault.js lookup secret-nodejs)
 
       - name: Delete secret with Python
-        run: vault -d 'secret-python'
+        run: |
+          vault -d 'secret-python' 2>&1 | tee output.log
+          test -f output.log || (echo "Error: output.log does not exist!" && exit 1)
+          test -s output.log && (echo "Unexpected output in Python vault delete command:" && cat output.log && exit 1)
+          rm -f output.log
 
       - name: Delete secret with Go
-        run: bin/go/vault -d 'secret-go'
+        run: |
+          bin/go/vault -d 'secret-go' 2>&1 | tee output.log
+          test -f output.log || (echo "Error: output.log does not exist!" && exit 1)
+          test -s output.log && (echo "Unexpected output in Go vault delete command:" && cat output.log && exit 1)
+          rm -f output.log
 
       - name: Delete secret with Rust
-        run: bin/rust/vault -d 'secret-rust'
+        run: |
+          bin/rust/vault -d 'secret-rust' 2>&1 | tee output.log
+          test -f output.log || (echo "Error: output.log does not exist!" && exit 1)
+          test -s output.log && (echo "Unexpected output in Rust vault delete command:" && cat output.log && exit 1)
+          rm -f output.log
 
       - name: Delete secret with Nodejs
-        run: nodejs/dist/cli/vault.js d 'secret-nodejs'
-
+        run: |
+          nodejs/dist/cli/vault.js d 'secret-nodejs' 2>&1 | tee output.log
+          test -f output.log || (echo "Error: output.log does not exist!" && exit 1)
+          test -s output.log && (echo "Unexpected output in Node.js vault delete command:" && cat output.log && exit 1)
+          rm -f output.log
       - name: Verify that 'secret-python' key has been deleted
         run: |
           bin/rust/vault exists secret-python | grep -q "key 'secret-python' does not exist"
